# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
            ],
        ),
    ]
