# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmodel',
            name='file',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AddField(
            model_name='empmodel',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
